const machines=[
{id:"MC-001",name:"Automatic Packing Machine",model:"PK-A120",line:"Packing Line 1",area:"Building A",status:"Running",damagePoints:["Photo Sensor","Conveyor","Sealing Unit","Motor","Control Panel"]},
{id:"MC-002",name:"CNC Milling Machine",model:"CNC-V500",line:"Machining Line 2",area:"Building B",status:"Running",damagePoints:["Spindle","Lubrication Unit","Servo Motor","Tool Changer","Control Panel"]},
{id:"MC-003",name:"Automatic Assembly Machine",model:"ASM-X300",line:"Assembly Line 1",area:"Building C",status:"Maintenance",damagePoints:["Cylinder","Robot Arm","Proximity Sensor","Feeder","Safety Door"]}
];
let repairHistory=[
{id:"WO-260901",machineId:"MC-001",date:"2026-09-01",point:"Control Panel",symptom:"หน้าจอ HMI ค้างและไม่ตอบสนอง",cause:"หน่วยความจำชั่วคราวเต็ม",action:"รีสตาร์ตระบบและอัปเดตโปรแกรม HMI",technician:"ธนกร",duration:35,status:"เสร็จสิ้น"},
{id:"WO-260828",machineId:"MC-001",date:"2026-08-28",point:"Photo Sensor",symptom:"เซนเซอร์ไม่ตรวจจับชิ้นงาน",cause:"หน้าสัมผัสสกปรก",action:"ทำความสะอาดและปรับตำแหน่ง",technician:"สมชาย",duration:25,status:"เสร็จสิ้น"},
{id:"WO-260815",machineId:"MC-001",date:"2026-08-15",point:"Sealing Unit",symptom:"อุณหภูมิชุดซีลไม่ถึงค่าที่กำหนด",cause:"ฮีตเตอร์เสื่อมสภาพ",action:"เปลี่ยนฮีตเตอร์และทดสอบอุณหภูมิ",technician:"อนันต์",duration:70,status:"เสร็จสิ้น"},
{id:"WO-260722",machineId:"MC-001",date:"2026-07-22",point:"Conveyor",symptom:"สายพานเคลื่อนที่ไม่สม่ำเสมอ",cause:"สายพานหย่อน",action:"ปรับความตึงสายพาน",technician:"วิชัย",duration:45,status:"เสร็จสิ้น"},
{id:"WO-260614",machineId:"MC-001",date:"2026-06-14",point:"Motor",symptom:"มอเตอร์มีความร้อนสูง",cause:"ลูกปืนเริ่มสึกหรอ",action:"เปลี่ยนลูกปืนมอเตอร์",technician:"อนันต์",duration:80,status:"เสร็จสิ้น"},
{id:"WO-260902",machineId:"MC-002",date:"2026-09-02",point:"Tool Changer",symptom:"ชุดเปลี่ยนทูลหยุดกลางตำแหน่ง",cause:"รอตรวจสอบสัญญาณ Servo",action:"เปิดใบงานและรอผู้เชี่ยวชาญตรวจสอบ",technician:"ประสิทธิ์",duration:40,status:"กำลังดำเนินการ"},
{id:"WO-260825",machineId:"MC-002",date:"2026-08-25",point:"Spindle",symptom:"มีเสียงดังขณะเดินเครื่อง",cause:"Bearing หลวม",action:"ตั้งระยะและตรวจสอบแรงสั่นสะเทือน",technician:"ประสิทธิ์",duration:65,status:"เสร็จสิ้น"},
{id:"WO-260811",machineId:"MC-002",date:"2026-08-11",point:"Servo Motor",symptom:"แกน X เคลื่อนที่กระตุก",cause:"ค่าการจูน Servo คลาดเคลื่อน",action:"ปรับค่า Servo Gain และทดสอบ",technician:"ธนกร",duration:90,status:"เสร็จสิ้น"},
{id:"WO-260730",machineId:"MC-002",date:"2026-07-30",point:"Lubrication Unit",symptom:"แรงดันน้ำมันต่ำ",cause:"ตัวกรองอุดตัน",action:"เปลี่ยนตัวกรอง",technician:"สมชาย",duration:35,status:"เสร็จสิ้น"},
{id:"WO-260829",machineId:"MC-003",date:"2026-08-29",point:"Cylinder",symptom:"กระบอกลมเคลื่อนที่ช้า",cause:"ซีลรั่ว",action:"รออะไหล่เปลี่ยน Seal Kit",technician:"วิชัย",duration:120,status:"รอดำเนินการ"},
{id:"WO-260817",machineId:"MC-003",date:"2026-08-17",point:"Proximity Sensor",symptom:"เครื่องไม่ยืนยันตำแหน่งชิ้นงาน",cause:"สายสัญญาณขาดภายใน",action:"เปลี่ยนสายและทดสอบสัญญาณ",technician:"สมชาย",duration:40,status:"เสร็จสิ้น"},
{id:"WO-260724",machineId:"MC-003",date:"2026-07-24",point:"Robot Arm",symptom:"แขนกลหยุดก่อนถึงตำแหน่งวาง",cause:"ตำแหน่ง Teaching คลาดเคลื่อน",action:"สอนตำแหน่งใหม่และทดสอบ Cycle",technician:"ธนกร",duration:85,status:"เสร็จสิ้น"},
{id:"WO-260703",machineId:"MC-003",date:"2026-07-03",point:"Feeder",symptom:"ชิ้นงานติดในรางป้อน",cause:"รางป้อนมีคราบน้ำมัน",action:"ทำความสะอาดและปรับแรงสั่น",technician:"อนันต์",duration:30,status:"เสร็จสิ้น"}
];
let priority="ปานกลาง";
const $=id=>document.getElementById(id);
const dateText=d=>new Intl.DateTimeFormat("th-TH",{day:"numeric",month:"short",year:"numeric"}).format(new Date(d+"T00:00:00"));
function currentMachine(){return machines.find(m=>m.id===$("machineSelect").value)||machines[0]}
function fillOptions(select,items,firstText,firstValue=""){select.innerHTML=`<option value="${firstValue}">${firstText}</option>`+items.map(x=>`<option value="${x}">${x}</option>`).join("")}
function renderMachine(){const m=currentMachine();$("machineName").textContent=m.name;$("machineModel").textContent=`Model: ${m.model}`;$("machineLine").textContent=m.line;$("machineArea").textContent=`📍 ${m.area}`;$("machineStatus").textContent=m.status==="Running"?"เดินเครื่อง":"กำลังซ่อม";$("machineStatus").className=`status ${m.status==="Running"?"running":"maintenance"}`;fillOptions($("damagePoint"),m.damagePoints,"เลือกจุดที่เสียหาย");fillOptions($("historyPoint"),m.damagePoints,"ทุกจุดที่เสียหาย","ทั้งหมด");$("historyCaption").textContent=`รายการของเครื่อง ${m.id} พร้อมตัวกรองหลายเงื่อนไข`;renderHistory()}
function filtered(){const id=$("machineSelect").value,p=$("historyPoint").value,s=$("startDate").value,e=$("endDate").value,q=$("searchInput").value.trim().toLowerCase();if(s&&e&&s>e)return[];return repairHistory.filter(r=>r.machineId===id).filter(r=>p==="ทั้งหมด"||r.point===p).filter(r=>!s||r.date>=s).filter(r=>!e||r.date<=e).filter(r=>!q||[r.id,r.point,r.symptom,r.cause,r.action,r.technician,r.status].join(" ").toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date))}
function statusClass(s){return s==="เสร็จสิ้น"?"done":s==="กำลังดำเนินการ"?"progress":"wait"}
function renderHistory(){const s=$("startDate").value,e=$("endDate").value,invalid=s&&e&&s>e;$("filterMessage").textContent=invalid?"วันที่เริ่มต้นต้องไม่เกินวันที่สิ้นสุด":"ระบบจะกรองและคำนวณ KPI ใหม่โดยอัตโนมัติ";$("filterMessage").parentElement.classList.toggle("error",invalid);const rows=filtered();$("repairCount").textContent=rows.length;$("mttr").textContent=rows.length?Math.round(rows.reduce((a,r)=>a+r.duration,0)/rows.length):0;$("latestPoint").textContent=rows[0]?.point||"-";$("historyList").innerHTML=rows.length?rows.map(r=>`<button class="history-item" data-id="${r.id}"><div class="history-top"><div class="history-title">🔧 ${r.point}<span class="badge ${statusClass(r.status)}">${r.status}</span></div><span class="history-date">${dateText(r.date)}</span></div><p class="history-symptom">${r.symptom}</p><div class="history-meta"><span>${r.id}</span><span>👤 ${r.technician}</span><span>◷ ${r.duration} นาที</span></div></button>`).join(""):`<div class="empty"><strong>ไม่พบประวัติการซ่อม</strong><p>ตรวจสอบช่วงวันที่หรือปรับเงื่อนไขตัวกรอง</p></div>`;document.querySelectorAll(".history-item").forEach(b=>b.onclick=()=>openModal(repairHistory.find(r=>r.id===b.dataset.id)))}
function openModal(r){$("modalId").textContent=r.id;$("modalContent").innerHTML=`<div class="detail"><small>วันที่ซ่อม</small><strong>${dateText(r.date)}</strong></div><div class="detail"><small>จุดที่ซ่อม</small><strong>${r.point}</strong></div><div class="detail"><small>สถานะ</small><span class="badge ${statusClass(r.status)}">${r.status}</span></div><div class="detail"><small>อาการเสีย</small><strong>${r.symptom}</strong></div><div class="detail"><small>สาเหตุ</small><strong>${r.cause}</strong></div><div class="detail"><small>การแก้ไข</small><strong>${r.action}</strong></div><div class="detail"><small>ผู้ซ่อม / เวลาซ่อม</small><strong>${r.technician} / ${r.duration} นาที</strong></div>`;$("modal").classList.remove("hidden")}
function closeModal(){$("modal").classList.add("hidden")}
$("machineSelect").innerHTML=machines.map(m=>`<option value="${m.id}">${m.id} • ${m.name}</option>`).join("");
$("machineSelect").onchange=()=>{["startDate","endDate","searchInput"].forEach(id=>$(id).value="");renderMachine()};
["historyPoint","startDate","endDate","searchInput"].forEach(id=>$(id).addEventListener("input",renderHistory));
$("clearFilters").onclick=()=>{$("historyPoint").value="ทั้งหมด";$("startDate").value="";$("endDate").value="";$("searchInput").value="";renderHistory()};
document.querySelectorAll(".priority").forEach(b=>b.onclick=()=>{priority=b.dataset.level;document.querySelectorAll(".priority").forEach(x=>x.classList.remove("active"));b.classList.add("active")});
$("photoInput").onchange=e=>$("fileName").textContent=e.target.files[0]?`ไฟล์ที่เลือก: ${e.target.files[0].name}`:"";
$("repairForm").onsubmit=e=>{e.preventDefault();const id=`WO-${Date.now().toString().slice(-6)}`,today=new Date().toISOString().slice(0,10);repairHistory.unshift({id,machineId:$("machineSelect").value,date:today,point:$("damagePoint").value,symptom:$("symptom").value.trim(),cause:"รอตรวจสอบ",action:`เปิดใบแจ้งซ่อมระดับความเร่งด่วน: ${priority}`,technician:"รอมอบหมาย",duration:0,status:"รอดำเนินการ"});$("successText").textContent=`สร้างใบแจ้งซ่อม ${id} เรียบร้อยแล้ว`;$("successMessage").classList.remove("hidden");$("repairForm").reset();$("fileName").textContent="";priority="ปานกลาง";document.querySelectorAll(".priority").forEach(x=>x.classList.toggle("active",x.dataset.level==="ปานกลาง"));renderMachine()};
$("closeSuccess").onclick=()=>$("successMessage").classList.add("hidden");$("closeModal").onclick=closeModal;$("closeModalBottom").onclick=closeModal;$("modal").onclick=e=>{if(e.target===$("modal"))closeModal()};document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});renderMachine();